# Generated by Django 5.2.1 on 2025-06-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
